version: '3'
services:
  php:
    container_name: rabbitmq-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9000:80"
  rabbitmq:
    container_name: rabmq-rabbitmq
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  rabbitmq-data: 
    driver: local
    
